# Generated by Django 4.1.6 on 2023-03-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collegeapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="duration",),
    ]
