# Generated by Django 4.1.6 on 2023-03-06 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("collegeapp", "0004_teacher"),
    ]

    operations = [
        migrations.RemoveField(model_name="teacher", name="age",),
    ]
